### ISSUE TITLE
Support Ruby apps that require NodeJS to run

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/ruby#464]
I have a ruby application that requires nodejs to run. When I provide both buildpacks, they appear to apply correctly, but then the application fails to run. It appears that nodejs isn't actually in the image.

This is the build command:
```
pack build app --buildpack gcr.io/paketo-buildpacks/ruby --buildpack gcr.io/paketo-buildpacks/node-engine
```

(Note: I also tried switching the order of the buildpacks and had the same issue.)

This is the error when running the image:
```
/layers/paketo-buildpacks_bundle-install/gems/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /layers/paketo-buildpacks_bundle-install/gems/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
	from /layers/paketo-buildpacks_bundler/bundler/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
	from /layers/paketo-buildpacks_bundler/bundler/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /layers/paketo-buildpacks_bundler/bundler/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
	from /layers/paketo-buildpacks_bundler/bundler/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
	from /layers/paketo-buildpacks_bundler/bundler/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
	from /layers/paketo-buildpacks_bundler/bundler/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
	from /layers/paketo-buildpacks_bundler/bundler/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
	from /workspace/config/application.rb:24:in `<top (required)>'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/railties-6.0.3.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/railties-6.0.3.1/lib/rails/command/base.rb:69:in `perform'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/railties-6.0.3.1/lib/rails/command.rb:46:in `invoke'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/railties-6.0.3.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /workspace/bin/rails:11:in `require'
	from /workspace/bin/rails:11:in `<top (required)>'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	from /layers/paketo-buildpacks_bundle-install/gems/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /workspace/bin/spring:16:in `require'
	from /workspace/bin/spring:16:in `<top (required)>'
	from bin/rails:5:in `load'
	from bin/rails:5:in `<main>'
```

With some guidance from @ryanmoran, I was able to build an image that works with this command:
```
pack build app --buildpack gcr.io/paketo-buildpacks/ruby --buildpack gcr.io/paketo-buildpacks/node-engine --buildpack https://github.com/paketo-community/build-plan/releases/download/v0.0.8/build-plan-v0.0.8.tgz
```

And a `plan.toml` that contains:
```toml
[[requires]]
  name = "node"
  version = "~10"
[requires.metadata]
  launch = true
```

**Comment by drnic** [comment]
Any luck on how to deploy a Rails app?

**Comment by genevieve** [comment]
Have there been any updates on supporting ruby apps that require nodejs to run?

**Comment by ryanmoran** [comment]
In practice, most Ruby (specifically Rails) applications should not need `node` to run in production. Instead, they should allow the `rails-assets` buildpack to precompile their Javascript assets during the build phase. The result of that buildpack will be a collection of static Javascript files that can simply be served by the Rails process without any `node` backend process involvement.

Additionally, the buildpacks make a preference for generating images that are more secure and more performant. In this case, producing an image that does not include `node` is more secure because the vulnerability surface area is reduced. It means that even if `node` has a vulnerability you won't need to rebuild your running applications because they don't contain a `node` installation that would be vulnerable. Its also a more performant image because its faster to fetch an smaller image from a registry.

**Comment by josegonzalez** [comment]
I have an app that loads sprockets-es6 on boot for the asset pipeline. While ideally this isn't the case and we only use node during build, I'm in the process of migrating an app with a ton of changes already made to support buildpacks, and it would be great to just have node available rather than me fighting with the buildpack.
