### ISSUE TITLE
Build failed to install mysql2 gem

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/ruby#862]
Reported [here](https://github.com/paketo-buildpacks/rfcs/pull/259#discussion_r1012639658).

Building a Ruby on Rails app with the following:
```
gem 'mysql', '>= 0.3.18', '< 0.5'
```

Fails with the following error:
```
[builder]       Installing mysql2 0.4.10 with native extensions
[builder]       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
[builder]       
[builder]       current directory:
[builder]       /layers/paketo-buildpacks_bundle-install/build-gems/gems/mysql2-0.4.10/ext/mysql2
[builder]       /layers/paketo-buildpacks_mri/mri/bin/ruby -I
[builder]       /layers/paketo-buildpacks_mri/mri/lib/ruby/2.7.0 -r
[builder]       ./siteconf20221102-70-45wmtq.rb extconf.rb
[builder]       checking for rb_absint_size()... yes
[builder]       checking for rb_absint_singlebit_p()... yes
[builder]       checking for ruby/thread.h... yes
[builder]       checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
[builder]       checking for rb_thread_blocking_region()... no
[builder]       checking for rb_wait_for_single_fd()... yes
[builder]       checking for rb_hash_dup()... yes
[builder]       checking for rb_intern3()... yes
[builder]       checking for rb_big_cmp()... yes
[builder]       *** extconf.rb failed ***
[builder]       Could not create Makefile due to some reason, probably lack of necessary
[builder]       libraries and/or headers.  Check the mkmf.log file for more details.  You may
[builder]       need configuration options.
[builder]       
[builder]       Provided configuration options:
[builder]       	--with-opt-dir
[builder]       	--without-opt-dir
[builder]       	--with-opt-include
[builder]       	--without-opt-include=${opt-dir}/include
[builder]       	--with-opt-lib
[builder]       	--without-opt-lib=${opt-dir}/lib
[builder]       	--with-make-prog
[builder]       	--without-make-prog
[builder]       	--srcdir=.
[builder]       	--curdir
[builder]       	--ruby=/layers/paketo-buildpacks_mri/mri/bin/$(RUBY_BASE_NAME)
[builder]       	--with-ruby-dir
[builder]       	--without-ruby-dir
[builder]       	--with-ruby-include
[builder]       	--without-ruby-include=${ruby-dir}/include
[builder]       	--with-ruby-lib
[builder]       	--without-ruby-lib=${ruby-dir}/lib
[builder]       	--with-mysql-dir
[builder]       	--without-mysql-dir
[builder]       	--with-mysql-include
[builder]       	--without-mysql-include=${mysql-dir}/include
[builder]       	--with-mysql-lib
[builder]       	--without-mysql-lib=${mysql-dir}/lib
[builder]       	--with-mysql-config
[builder]       	--without-mysql-config
[builder]       	--with-mysqlclient-dir
[builder]       	--without-mysqlclient-dir
[builder]       	--with-mysqlclient-include
[builder]       	--without-mysqlclient-include=${mysqlclient-dir}/include
[builder]       	--with-mysqlclient-lib
[builder]       	--without-mysqlclient-lib=${mysqlclient-dir}/lib
[builder]       	--with-mysqlclientlib
[builder]       	--without-mysqlclientlib
[builder]       /layers/paketo-buildpacks_mri/mri/lib/ruby/2.7.0/mkmf.rb:1050:in `block in
[builder]       find_library': undefined method `split' for nil:NilClass (NoMethodError)
[builder]       	from /layers/paketo-buildpacks_mri/mri/lib/ruby/2.7.0/mkmf.rb:1050:in `collect'
[builder]       from /layers/paketo-buildpacks_mri/mri/lib/ruby/2.7.0/mkmf.rb:1050:in
[builder]       `find_library'
[builder]       	from extconf.rb:95:in `<main>'
[builder]       
[builder]       To see why this extension failed to compile, please check the mkmf.log which can
[builder]       be found here:
[builder]       
[builder]       /layers/paketo-buildpacks_bundle-install/build-gems/extensions/x86_64-linux/2.7.0-static/mysql2-0.4.10/mkmf.log
[builder]       
[builder]       extconf failed, exit code 1
[builder]       
[builder]       Gem files will remain installed in
[builder]       /layers/paketo-buildpacks_bundle-install/build-gems/gems/mysql2-0.4.10 for
[builder]       inspection.
[builder]       Results logged to
[builder]       /layers/paketo-buildpacks_bundle-install/build-gems/extensions/x86_64-linux/2.7.0-static/mysql2-0.4.10/gem_make.out
[builder]       
[builder]       An error occurred while installing mysql2 (0.4.10), and Bundler cannot continue.
[builder]       Make sure that `gem install mysql2 -v '0.4.10' --source 'https://rubygems.org/'`
[builder]       succeeds before bundling.
[builder]       
[builder]       In Gemfile:
[builder]         mysql2
[builder] failed to execute bundle install output:
[builder] 
[builder] error: exit status 5
[builder] ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51
```

People are reporting that [installing of default-libmysqlclient-dev will help]( https://github.com/brianmario/mysql2/issues/1160).

**Comment by dmikusa** [comment]
Not sure if it's the issue here, but I've had [this change in Ubuntu](https://unix.stackexchange.com/questions/586792/difference-between-usr-lib-and-usr-lib-x86-64-linux-gnu-folders) cause package builds to fail for me even when the required dev libraries are installed. Just a suggestion.

**Comment by robdimsdale** [comment]
I've validated on a stock ubuntu setup that adding `default-libmysqlclient-dev` is necessary to run `gem install mysql2` (and a rails app that uses it to talk to a mysql database).

I've also validated that a rails app with the `mysql2` gem fails to build on the full stack for the same reason as above.

Next step - we can add the `default-libmysqlclient-dev` library to the full stack and see if that fixes the issue.

**Comment by cz4rny** [comment]
> @cz4rny can you help me understand what you did differently with your rails app (with `mysql2` gem) such that you saw it fail? I can't reproduce it.

I'll try my best, although I'm not a RoR dev, but a DevOps guy trying to make a legacy app deploy to the newer infrastructure. For that I'm pasting the gemfile stuff, so you can see if anything is different.

```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 5.4.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
gem 'mini_racer', platforms: :ruby
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
# Use Figaro gem to easily manage secrets
gem 'figaro'
# Use Bootstrap for easy pretty
gem 'bootstrap', '~> 4.1.3'
# Net-LDAP gem for handling login internally accross the company
# gem 'net-ldap'
# Kaminari for handling pagination
# gem 'kaminari'
# Font-Awesome for cool looking icons
gem 'font-awesome-rails'
# # jquery-turbolinks for getting Turbolinks to work with Angular
# gem 'jquery-turbolinks'

gem 'seed_dump'

# Use Capistrano for deployment
#gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'pry'
  gem 'rspec-rails'
  gem 'better_errors'
end


group :development do
  gem "capistrano", "~> 3.7"
  gem "capistrano-rails", "~> 1.2"
  gem "capistrano-passenger", "~> 0.2.0"
  gem "capistrano-yarn"
  #Add this if you"re using rbenv
  gem "capistrano-rbenv", "~> 2.1"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

```yaml
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.7.2)
      actionpack (= 5.0.7.2)
      nio4r (>= 1.2, < 3.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.7.2)
      actionpack (= 5.0.7.2)
      actionview (= 5.0.7.2)
      activejob (= 5.0.7.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.7.2)
      actionview (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.7.2)
      activesupport (= 5.0.7.2)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.0.7.2)
      activesupport (= 5.0.7.2)
      globalid (>= 0.3.6)
    activemodel (5.0.7.2)
      activesupport (= 5.0.7.2)
    activerecord (5.0.7.2)
      activemodel (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      arel (~> 7.0)
    activesupport (5.0.7.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    airbrussh (1.3.2)
      sshkit (>= 1.6.1, != 1.7.0)
    arel (7.1.4)
    autoprefixer-rails (9.6.1)
      execjs
    bcrypt (3.1.13)
    better_errors (2.5.1)
      coderay (>= 1.0.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
    bindex (0.8.1)
    bootstrap (4.1.3)
      autoprefixer-rails (>= 6.0.3)
      popper_js (>= 1.12.9, < 2)
      sass (>= 3.5.2)
    builder (3.2.3)
    byebug (11.0.1)
    capistrano (3.11.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.6.0)
      capistrano (~> 3.1)
    capistrano-passenger (0.2.0)
      capistrano (~> 3.0)
    capistrano-rails (1.4.0)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rbenv (2.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    capistrano-yarn (2.0.2)
      capistrano (~> 3.0)
    coderay (1.1.2)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.5)
    crass (1.0.4)
    diff-lcs (1.3)
    erubi (1.8.0)
    erubis (2.7.0)
    execjs (2.7.0)
    ffi (1.11.1)
    figaro (1.1.1)
      thor (~> 0.14)
    font-awesome-rails (4.7.0.5)
      railties (>= 3.2, < 6.1)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    jbuilder (2.9.1)
      activesupport (>= 4.2.0)
    jquery-rails (4.3.5)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    libv8 (7.3.492.27.1)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    method_source (0.9.2)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    mini_racer (0.2.6)
      libv8 (>= 6.9.411)
    minitest (5.12.0)
    mysql2 (0.4.10)
    net-scp (2.0.0)
      net-ssh (>= 2.6.5, < 6.0.0)
    net-ssh (5.2.0)
    nio4r (2.5.2)
    nokogiri (1.10.4)
      mini_portile2 (~> 2.4.0)
    popper_js (1.14.5)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    puma (5.4.0)
      nio4r (~> 2.0)
    rack (2.0.7)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.7.2)
      actioncable (= 5.0.7.2)
      actionmailer (= 5.0.7.2)
      actionpack (= 5.0.7.2)
      actionview (= 5.0.7.2)
      activejob (= 5.0.7.2)
      activemodel (= 5.0.7.2)
      activerecord (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      bundler (>= 1.3.0)
      railties (= 5.0.7.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.2.0)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.0.7.2)
      actionpack (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.3)
    rb-fsevent (0.10.3)
    rb-inotify (0.10.0)
      ffi (~> 1.0)
    rspec-core (3.8.2)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.4)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-rails (3.8.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.2)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    seed_dump (3.3.1)
      activerecord (>= 4)
      activesupport (>= 4)
    spring (2.1.0)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.20.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.10)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.20)
      execjs (>= 0.3.0, < 3)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)

PLATFORMS
  ruby

DEPENDENCIES
  bcrypt (~> 3.1.7)
  better_errors
  bootstrap (~> 4.1.3)
  byebug
  capistrano (~> 3.7)
  capistrano-passenger (~> 0.2.0)
  capistrano-rails (~> 1.2)
  capistrano-rbenv (~> 2.1)
  capistrano-yarn
  coffee-rails (~> 4.2)
  figaro
  font-awesome-rails
  jbuilder (~> 2.5)
  jquery-rails
  listen (~> 3.0.5)
  mini_racer
  mysql2 (>= 0.3.18, < 0.5)
  pry
  puma (~> 5.4.0)
  rails (~> 5.0.1)
  rspec-rails
  sass-rails (~> 5.0)
  seed_dump
  spring
  spring-watcher-listen (~> 2.0.0)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   1.17.3
```

**Comment by cz4rny** [comment]
And now looking at it from afar it seems that I'm using the **base** base image instead of the **full** one. Let me re-try with the full one. Fingers crossed!

**Comment by cz4rny** [comment]
Alright! This time, when using the **full** builder image it indeed installed the `mysql2` dependency with its native extensions. That's great news for me. Thank you so much for debugging this essentially for me!

**Comment by robdimsdale** [comment]
Oh, great! I'm glad to hear this worked. I'll close this issue and remove the [associated RFC](https://github.com/paketo-buildpacks/rfcs/pull/259).
